name: CI

on:
  push:
  pull_request:
  release:
    types:
      - published

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - elixir: 1.11
            otp: 23.0
            deploy: true
          - elixir: 1.11
            otp: 23.0
            html_parser: meeseeks
          - elixir: 1.7
            otp: 20.0
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}} / ${{matrix.html_parser}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - run: mix deps.get
      - run: mix format --check-formatted
      - run: MIX_ENV=test mix credo
      - run: mix test
        env:
          HTML_PARSER: ${{ matrix.html_parser }}
  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    name: Deploy published release
    env:
      HEX_API_KEY: ${{secrets.HEX_API_KEY}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: 23.0
          elixir-version: 1.11
      - run: mix deps.get
      - run: mix hex.publish --yes
