name: CI

on:
  push: 
    branches: [ main ]
  pull_request:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Linter
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 28.0
          elixir-version: 1.19
      - uses: actions/cache@v4
        env:
          cache-name: ${{ github.event.repository.name }}-plt
        with:
          path: |
            _build
            deps
          key: ${{ runner.os }}-mix-${{ env.cache-name }}-${{ hashFiles('mix.lock') }}
      - run: mix deps.get
      - run: mix compile --warnings-as-errors
      - run: mix credo --strict
      - run: mix format --check-formatted
      - run: mix dialyzer --format github

  test:
    strategy:
      matrix:
        html_parser: [floki, meeseeks]
        version:
          - otp: 28.0
            elixir: 1.19
            os: ubuntu-latest
          - otp: 24.0
            elixir: 1.14
            os: ubuntu-latest

    runs-on: ${{ matrix.version.os }}
    name: OTP ${{matrix.version.otp}} / Elixir ${{matrix.version.elixir}} / ${{matrix.html_parser}}
    env:
      MIX_ENV: test
      HTML_PARSER: ${{matrix.html_parser}}
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.version.otp}}
          elixir-version: ${{matrix.version.elixir}}
      - run: mix deps.get
      - run: mix compile --warnings-as-errors
      - run: mix test
